### ISSUE TITLE
Documentation minor issue

### ISSUE THREAD

**Issue by tomasantunes** [hiltonjanfield/jquery.enhsplitter#20]
Hi, I'm trying to replicate the demo number 3 in the documentation, but the code on the right and the explanation on the left are contradictory in how to pull off the effect.

**Comment by hiltonjanfield** [comment]
In the demo, it states:
#demoThreeA - Sidebar Example with fixed splitter
#demoThreeB - This splitter was created using with the options {`handle: 'bar', position: 150, leftMinSize: 30, fixed: true}`. `position` defines a starting size, `{limit, lowerLimit, and upperLimit}` define how small the panels may get, and handle sets up a different effect for the collapse handle. The `{fixed: true}` option disables the ability to drag the splitter around, while leaving the collapse options intact - the result being an unmovable bar with a button that collapses it back and forth. 

The code on the right shows (relevant portions only):

```
<div id="demoThree">
    <div id="demoThreeA">
        [...]
    </div>
    <div id="demoThreeB">
        [...]
    </div>
</div>

<script>
    jQuery(function ($) {
        $('#demoThree').enhsplitter({handle: 'bar', position: 150, lowerLimit: 0, upperLimit: 150, fixed: true});
    });
</script>
```

The options shown on the left and right are identical. I do not see how it is in any way contradictory.

You will find nearly the exact same code and an explanation under **Usage** immediately below the demos. As explained therein, when creating a panel, you ALWAYS need three containers. One outer container and two inner ones. Calling `.enhsplitter()` on the outer container will generate your panel with the options you supply.

If you are still having trouble, please show your code so I can review it.

**Comment by tomasantunes** [comment]
There clearly is a big difference between "{handle: 'bar', position: 150, leftMinSize: 30, fixed: true}" and "{handle: 'bar', position: 150, lowerLimit: 0, upperLimit: 150, fixed: true}" 

both these code samples seem to refer to the same example.

**Comment by hiltonjanfield** [comment]
Oh my god I am an idiot.

Sorry. That was a leftover from an old option; the original had a 'limit' option which I expanded into upper/lower, but then renamed to the *size options. Obviously I missed a spot!

Thank you for pointing out my mistake. Have fixed.
